version: "3.7"

services:
    db:
        image: mysql:5.7
        volumes:
          - "/app/ksc/var/lib/mysql:/var/lib/mysql"
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: "@chocon"
        ports:
          - "3306:3306"
            
    api:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
          - "/app/ksc/api:/app"
        depends_on:
          - db
        environment:
          #https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.2
          ASPNETCORE_ENVIRONMENT: "Staging" #Development || Production || Staging
        ports:
          - "5000:5000"
          - "5001:5001"
        restart: always

    web:
        build:
            context: src/web
            dockerfile: Dockerfile
        volumes:
          - "/app/ksc/web:/app"
        depends_on:
            - api
        ports:
            - "3000:3000"
        restart: always