version: "3.7"

services:
    db:
        image: mysql:5.7
        volumes:
          - "/home/database:/var/lib/mysql"
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: "@chocon"
        ports:
          - "3306:3306"
            
    api:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
          - db
        environment:
          ASPNETCORE_ENVIRONMENT: "Development" #Production || Staging
        ports:
          - "8000:8000"
        restart: always

    web:
        build:
            context: src/web
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "3000:3000"
        restart: always