version: '3.0'
 
services:
   dbContext:
     image: mysql:5.7
     environment:
       MYSQL_USER: root
       MYSQL_PASSWORD: @chocon
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
 
   kscApi:
     depends_on:
       - dbContext
     image: kscApi
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - "8080:80"
 
volumes:
    dbdata: