FROM node:8 as node-env

COPY . /app

WORKDIR /app

RUN npm install

RUN npm run build

FROM nginx:latest

WORKDIR /

RUN rm -r /usr/share/nginx/html*

COPY --from=node-env /app/web/. /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]